apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
    app: rwhois
    status: {{ .Values.status }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
      app: rwhois
      status: {{ .Values.status }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
        app: rwhois
        status: {{ .Values.status }}
    spec:
      imagePullSecrets:
       - name: {{ .Values.imagePullSecrets }}
      containers:
        - name: {{ .Chart.Name }}
          tty: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_DBHOST
              value: BLANK_SPACE
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # readinessProbe:
          #   tcpSocket:
          #     port: 3000
          #   initialDelaySeconds: 20
          #   periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - bash
            - c
            #- "bundle exec rails server -b 0.0.0.0"
          volumeMounts:
          - name: database-config
            mountPath: "/opt/webapps/app/config/database.yml"
            subPath: "database.yml"
      volumes:
       - name: database-config
         configMap:
           name: {{ .Values.configmap.database }}

